
# This file is automatically generated, you probably don't want to edit this

cartoOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "cartoOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            coox = NULL,
            cooy = NULL,
            group = NULL, ...) {

            super$initialize(
                package="SEDA",
                name="carto",
                requiresData=TRUE,
                ...)

            private$..coox <- jmvcore::OptionVariable$new(
                "coox",
                coox,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"))
            private$..cooy <- jmvcore::OptionVariable$new(
                "cooy",
                cooy,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"))
            private$..group <- jmvcore::OptionVariables$new(
                "group",
                group,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"))

            self$.addOption(private$..coox)
            self$.addOption(private$..cooy)
            self$.addOption(private$..group)
        }),
    active = list(
        coox = function() private$..coox$value,
        cooy = function() private$..cooy$value,
        group = function() private$..group$value),
    private = list(
        ..coox = NA,
        ..cooy = NA,
        ..group = NA)
)

cartoResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "cartoResults",
    inherit = jmvcore::Group,
    active = list(
        plotcarto = function() private$.items[["plotcarto"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="External Preference Mapping")
            self$add(jmvcore::Image$new(
                options=options,
                name="plotcarto",
                title="Representation of the Products",
                width=400,
                height=300,
                renderFun=".plotcartograph"))}))

cartoBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "cartoBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "SEDA",
                name = "carto",
                version = c(1,0,0),
                options = options,
                results = cartoResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE)
        }))

#' External Preference Mapping
#'
#' 
#' @param data .
#' @param coox .
#' @param cooy .
#' @param group .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$plotcarto} \tab \tab \tab \tab \tab an image \cr
#' }
#'
#' @export
carto <- function(
    data,
    coox,
    cooy,
    group) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("carto requires jmvcore to be installed (restart may be required)")

    if ( ! missing(coox)) coox <- jmvcore::resolveQuo(jmvcore::enquo(coox))
    if ( ! missing(cooy)) cooy <- jmvcore::resolveQuo(jmvcore::enquo(cooy))
    if ( ! missing(group)) group <- jmvcore::resolveQuo(jmvcore::enquo(group))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(coox), coox, NULL),
            `if`( ! missing(cooy), cooy, NULL),
            `if`( ! missing(group), group, NULL))


    options <- cartoOptions$new(
        coox = coox,
        cooy = cooy,
        group = group)

    analysis <- cartoClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

