
# This file is automatically generated, you probably don't want to edit this

cataOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "cataOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            cordo = NULL,
            group = NULL, ...) {

            super$initialize(
                package="SEDA",
                name="cata",
                requiresData=TRUE,
                ...)

            private$..cordo <- jmvcore::OptionVariable$new(
                "cordo",
                cordo)
            private$..group <- jmvcore::OptionVariables$new(
                "group",
                group,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"))

            self$.addOption(private$..cordo)
            self$.addOption(private$..group)
        }),
    active = list(
        cordo = function() private$..cordo$value,
        group = function() private$..group$value),
    private = list(
        ..cordo = NA,
        ..group = NA)
)

cataResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "cataResults",
    inherit = jmvcore::Group,
    active = list(
        textualgroup = function() private$.items[["textualgroup"]],
        dfresgroup = function() private$.items[["dfresgroup"]],
        plotcata = function() private$.items[["plotcata"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Analysis of CATA data")
            self$add(R6::R6Class(
                inherit = jmvcore::Group,
                active = list(
                    textual = function() private$.items[["textual"]]),
                private = list(),
                public=list(
                    initialize=function(options) {
                        super$initialize(
                            options=options,
                            name="textualgroup",
                            title="Contingency Table")
                        self$add(jmvcore::Table$new(
                            options=options,
                            name="textual",
                            title="",
                            visible="(cordo)",
                            clearWith=list(
                                "cordo",
                                "group"),
                            columns=list()))}))$new(options=options))
            self$add(R6::R6Class(
                inherit = jmvcore::Group,
                active = list(
                    dfres = function() private$.items[["dfres"]]),
                private = list(),
                public=list(
                    initialize=function(options) {
                        super$initialize(
                            options=options,
                            name="dfresgroup",
                            title="Description of the Products According to CATA")
                        self$add(jmvcore::Table$new(
                            options=options,
                            name="dfres",
                            title="Description of the Products According to CATA",
                            visible="(cordo)",
                            columns=list(
                                list(
                                    `name`="component", 
                                    `title`="", 
                                    `type`="text", 
                                    `combineBelow`=TRUE),
                                list(
                                    `name`="word", 
                                    `title`="Word", 
                                    `type`="text"),
                                list(
                                    `name`="internper", 
                                    `title`="Intern %", 
                                    `type`="Number"),
                                list(
                                    `name`="globper", 
                                    `title`="Global %", 
                                    `type`="Number"),
                                list(
                                    `name`="internfreq", 
                                    `title`="Intern frequency", 
                                    `type`="Number"),
                                list(
                                    `name`="globfreq", 
                                    `title`="Global frequency", 
                                    `type`="Number"),
                                list(
                                    `name`="pvaluedfres", 
                                    `title`="p", 
                                    `format`="zto,pvalue"),
                                list(
                                    `name`="vtest", 
                                    `title`="Vtest", 
                                    `type`="Number"))))}))$new(options=options))
            self$add(jmvcore::Image$new(
                options=options,
                name="plotcata",
                title="Representation of the Products and the CATA",
                width=600,
                height=500,
                renderFun=".plotcatatis"))}))

cataBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "cataBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "SEDA",
                name = "cata",
                version = c(1,0,0),
                options = options,
                results = cataResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE)
        }))

#' Analysis of CATA data
#'
#' 
#' @param data .
#' @param cordo .
#' @param group .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$textualgroup$textual} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$dfresgroup$dfres} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$plotcata} \tab \tab \tab \tab \tab an image \cr
#' }
#'
#' @export
cata <- function(
    data,
    cordo,
    group) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("cata requires jmvcore to be installed (restart may be required)")

    if ( ! missing(cordo)) cordo <- jmvcore::resolveQuo(jmvcore::enquo(cordo))
    if ( ! missing(group)) group <- jmvcore::resolveQuo(jmvcore::enquo(group))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(cordo), cordo, NULL),
            `if`( ! missing(group), group, NULL))


    options <- cataOptions$new(
        cordo = cordo,
        group = group)

    analysis <- cataClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

