
# This file is automatically generated, you probably don't want to edit this

JAROptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "JAROptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            prodeff = NULL,
            paneff = NULL,
            likvar = NULL,
            sensoatt = NULL,
            jarmod = "jar", ...) {

            super$initialize(
                package="SEDA",
                name="JAR",
                requiresData=TRUE,
                ...)

            private$..prodeff <- jmvcore::OptionVariable$new(
                "prodeff",
                prodeff,
                suggested=list(
                    "nominal"),
                permitted=list(
                    "factor"))
            private$..paneff <- jmvcore::OptionVariable$new(
                "paneff",
                paneff,
                suggested=list(
                    "nominal"),
                permitted=list(
                    "factor"))
            private$..likvar <- jmvcore::OptionVariable$new(
                "likvar",
                likvar,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"))
            private$..sensoatt <- jmvcore::OptionVariables$new(
                "sensoatt",
                sensoatt,
                suggested=list(
                    "nominal"),
                permitted=list(
                    "factor"))
            private$..jarmod <- jmvcore::OptionString$new(
                "jarmod",
                jarmod,
                default="jar")

            self$.addOption(private$..prodeff)
            self$.addOption(private$..paneff)
            self$.addOption(private$..likvar)
            self$.addOption(private$..sensoatt)
            self$.addOption(private$..jarmod)
        }),
    active = list(
        prodeff = function() private$..prodeff$value,
        paneff = function() private$..paneff$value,
        likvar = function() private$..likvar$value,
        sensoatt = function() private$..sensoatt$value,
        jarmod = function() private$..jarmod$value),
    private = list(
        ..prodeff = NA,
        ..paneff = NA,
        ..likvar = NA,
        ..sensoatt = NA,
        ..jarmod = NA)
)

JARResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "JARResults",
    inherit = jmvcore::Group,
    active = list(
        frequencebrut = function() private$.items[["frequencebrut"]],
        frequencebrutdes = function() private$.items[["frequencebrutdes"]],
        plotjar = function() private$.items[["plotjar"]],
        penalty = function() private$.items[["penalty"]],
        frequence = function() private$.items[["frequence"]],
        plotpen = function() private$.items[["plotpen"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Analysis of JAR data")
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="frequencebrut",
                title="Contingency Table (Defects by Products)"))
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="frequencebrutdes",
                title="Description of the Products According to Defects"))
            self$add(jmvcore::Image$new(
                options=options,
                name="plotjar",
                title="Representation of the Products and the Defects",
                width=600,
                height=500,
                renderFun=".plotboth"))
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="penalty",
                title="Penalties Obtained from All Defects"))
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="frequence",
                title="Frequencies of Defects by Product and Sensory Attribute"))
            self$add(jmvcore::Image$new(
                options=options,
                name="plotpen",
                title="Representation of the Penalties for the First Product",
                width=600,
                height=500,
                renderFun=".plotpenalty"))}))

JARBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "JARBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "SEDA",
                name = "JAR",
                version = c(1,0,0),
                options = options,
                results = JARResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE)
        }))

#' Analysis of JAR data
#'
#' 
#' @param data .
#' @param prodeff .
#' @param paneff .
#' @param likvar .
#' @param sensoatt .
#' @param jarmod .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$frequencebrut} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$frequencebrutdes} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$plotjar} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$penalty} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$frequence} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$plotpen} \tab \tab \tab \tab \tab an image \cr
#' }
#'
#' @export
JAR <- function(
    data,
    prodeff,
    paneff,
    likvar,
    sensoatt,
    jarmod = "jar") {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("JAR requires jmvcore to be installed (restart may be required)")

    if ( ! missing(prodeff)) prodeff <- jmvcore::resolveQuo(jmvcore::enquo(prodeff))
    if ( ! missing(paneff)) paneff <- jmvcore::resolveQuo(jmvcore::enquo(paneff))
    if ( ! missing(likvar)) likvar <- jmvcore::resolveQuo(jmvcore::enquo(likvar))
    if ( ! missing(sensoatt)) sensoatt <- jmvcore::resolveQuo(jmvcore::enquo(sensoatt))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(prodeff), prodeff, NULL),
            `if`( ! missing(paneff), paneff, NULL),
            `if`( ! missing(likvar), likvar, NULL),
            `if`( ! missing(sensoatt), sensoatt, NULL))

    for (v in prodeff) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])
    for (v in paneff) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])
    for (v in sensoatt) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])

    options <- JAROptions$new(
        prodeff = prodeff,
        paneff = paneff,
        likvar = likvar,
        sensoatt = sensoatt,
        jarmod = jarmod)

    analysis <- JARClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

