
# This file is automatically generated, you probably don't want to edit this

NappingOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "NappingOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            actvars = NULL,
            quantisup = NULL,
            qualisup = NULL,
            individus = NULL,
            nFactors = 3,
            corvar = FALSE,
            contribvar = FALSE,
            cosvar = FALSE,
            coordind = FALSE,
            contribind = FALSE,
            cosind = FALSE,
            proba = 5,
            abs = 1,
            ord = 2,
            varact = FALSE,
            varillus = FALSE,
            varactillus = TRUE,
            limcosvar = 0,
            modact = FALSE,
            modillus = FALSE,
            modactillus = TRUE, ...) {

            super$initialize(
                package="SEDA",
                name="Napping",
                requiresData=TRUE,
                ...)

            private$..actvars <- jmvcore::OptionVariables$new(
                "actvars",
                actvars,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"))
            private$..quantisup <- jmvcore::OptionVariables$new(
                "quantisup",
                quantisup,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"))
            private$..qualisup <- jmvcore::OptionVariables$new(
                "qualisup",
                qualisup,
                suggested=list(
                    "nominal",
                    "ordinal"),
                permitted=list(
                    "factor"))
            private$..individus <- jmvcore::OptionVariable$new(
                "individus",
                individus,
                suggested=list(
                    "nominal"),
                permitted=list(
                    "factor"))
            private$..nFactors <- jmvcore::OptionInteger$new(
                "nFactors",
                nFactors,
                default=3)
            private$..corvar <- jmvcore::OptionBool$new(
                "corvar",
                corvar,
                default=FALSE)
            private$..contribvar <- jmvcore::OptionBool$new(
                "contribvar",
                contribvar,
                default=FALSE)
            private$..cosvar <- jmvcore::OptionBool$new(
                "cosvar",
                cosvar,
                default=FALSE)
            private$..coordind <- jmvcore::OptionBool$new(
                "coordind",
                coordind,
                default=FALSE)
            private$..contribind <- jmvcore::OptionBool$new(
                "contribind",
                contribind,
                default=FALSE)
            private$..cosind <- jmvcore::OptionBool$new(
                "cosind",
                cosind,
                default=FALSE)
            private$..proba <- jmvcore::OptionNumber$new(
                "proba",
                proba,
                default=5)
            private$..abs <- jmvcore::OptionInteger$new(
                "abs",
                abs,
                default=1)
            private$..ord <- jmvcore::OptionInteger$new(
                "ord",
                ord,
                default=2)
            private$..varact <- jmvcore::OptionBool$new(
                "varact",
                varact,
                default=FALSE)
            private$..varillus <- jmvcore::OptionBool$new(
                "varillus",
                varillus,
                default=FALSE)
            private$..varactillus <- jmvcore::OptionBool$new(
                "varactillus",
                varactillus,
                default=TRUE)
            private$..limcosvar <- jmvcore::OptionNumber$new(
                "limcosvar",
                limcosvar,
                default=0)
            private$..modact <- jmvcore::OptionBool$new(
                "modact",
                modact,
                default=FALSE)
            private$..modillus <- jmvcore::OptionBool$new(
                "modillus",
                modillus,
                default=FALSE)
            private$..modactillus <- jmvcore::OptionBool$new(
                "modactillus",
                modactillus,
                default=TRUE)

            self$.addOption(private$..actvars)
            self$.addOption(private$..quantisup)
            self$.addOption(private$..qualisup)
            self$.addOption(private$..individus)
            self$.addOption(private$..nFactors)
            self$.addOption(private$..corvar)
            self$.addOption(private$..contribvar)
            self$.addOption(private$..cosvar)
            self$.addOption(private$..coordind)
            self$.addOption(private$..contribind)
            self$.addOption(private$..cosind)
            self$.addOption(private$..proba)
            self$.addOption(private$..abs)
            self$.addOption(private$..ord)
            self$.addOption(private$..varact)
            self$.addOption(private$..varillus)
            self$.addOption(private$..varactillus)
            self$.addOption(private$..limcosvar)
            self$.addOption(private$..modact)
            self$.addOption(private$..modillus)
            self$.addOption(private$..modactillus)
        }),
    active = list(
        actvars = function() private$..actvars$value,
        quantisup = function() private$..quantisup$value,
        qualisup = function() private$..qualisup$value,
        individus = function() private$..individus$value,
        nFactors = function() private$..nFactors$value,
        corvar = function() private$..corvar$value,
        contribvar = function() private$..contribvar$value,
        cosvar = function() private$..cosvar$value,
        coordind = function() private$..coordind$value,
        contribind = function() private$..contribind$value,
        cosind = function() private$..cosind$value,
        proba = function() private$..proba$value,
        abs = function() private$..abs$value,
        ord = function() private$..ord$value,
        varact = function() private$..varact$value,
        varillus = function() private$..varillus$value,
        varactillus = function() private$..varactillus$value,
        limcosvar = function() private$..limcosvar$value,
        modact = function() private$..modact$value,
        modillus = function() private$..modillus$value,
        modactillus = function() private$..modactillus$value),
    private = list(
        ..actvars = NA,
        ..quantisup = NA,
        ..qualisup = NA,
        ..individus = NA,
        ..nFactors = NA,
        ..corvar = NA,
        ..contribvar = NA,
        ..cosvar = NA,
        ..coordind = NA,
        ..contribind = NA,
        ..cosind = NA,
        ..proba = NA,
        ..abs = NA,
        ..ord = NA,
        ..varact = NA,
        ..varillus = NA,
        ..varactillus = NA,
        ..limcosvar = NA,
        ..modact = NA,
        ..modillus = NA,
        ..modactillus = NA)
)

NappingResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "NappingResults",
    inherit = jmvcore::Group,
    active = list(
        plotind = function() private$.items[["plotind"]],
        plotind2 = function() private$.items[["plotind2"]],
        plotind3 = function() private$.items[["plotind3"]],
        plotvar = function() private$.items[["plotvar"]],
        plotvar2 = function() private$.items[["plotvar2"]],
        plotvar3 = function() private$.items[["plotvar3"]],
        plotgrp = function() private$.items[["plotgrp"]],
        eigengroup = function() private$.items[["eigengroup"]],
        descdesdim = function() private$.items[["descdesdim"]],
        individus = function() private$.items[["individus"]],
        variables = function() private$.items[["variables"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Analysis of Napping Data")
            self$add(jmvcore::Image$new(
                options=options,
                name="plotind",
                visible="(modactillus)",
                title="Representation of the Stimuli (and Categorical Supplementary Variables)",
                width=800,
                height=600,
                renderFun=".plotindividus"))
            self$add(jmvcore::Image$new(
                options=options,
                name="plotind2",
                visible="(modact)",
                title="Representation of the Stimuli",
                width=800,
                height=600,
                renderFun=".plotindividus2"))
            self$add(jmvcore::Image$new(
                options=options,
                name="plotind3",
                visible="(modillus)",
                title="Representation of the Categorical Supplementary Variables",
                width=800,
                height=600,
                renderFun=".plotindividus3"))
            self$add(jmvcore::Image$new(
                options=options,
                name="plotvar",
                visible="(varactillus)",
                title="Representation of the Active and Supplementary Variables",
                width=600,
                height=600,
                renderFun=".plotvariables"))
            self$add(jmvcore::Image$new(
                options=options,
                name="plotvar2",
                visible="(varact)",
                title="Representation of the Active Variables",
                width=600,
                height=600,
                renderFun=".plotvariables2"))
            self$add(jmvcore::Image$new(
                options=options,
                name="plotvar3",
                visible="(varillus)",
                title="Representation of the Supplementary Variables",
                width=600,
                height=600,
                renderFun=".plotvariables3"))
            self$add(jmvcore::Image$new(
                options=options,
                name="plotgrp",
                title="Representation of the Subjects",
                width=600,
                height=600,
                renderFun=".plotgroups"))
            self$add(R6::R6Class(
                inherit = jmvcore::Group,
                active = list(
                    eigen = function() private$.items[["eigen"]]),
                private = list(),
                public=list(
                    initialize=function(options) {
                        super$initialize(
                            options=options,
                            name="eigengroup",
                            title="Eigenvalue Decomposition")
                        self$add(jmvcore::Table$new(
                            options=options,
                            name="eigen",
                            title="Eigenvalue and (Cumulative) Percentage of Variance",
                            columns=list(
                                list(
                                    `name`="component", 
                                    `title`="", 
                                    `type`="text"),
                                list(
                                    `name`="eigenvalue", 
                                    `title`="Eigenvalue", 
                                    `type`="number"),
                                list(
                                    `name`="purcent", 
                                    `title`="% of the variance", 
                                    `type`="number"),
                                list(
                                    `name`="purcentcum", 
                                    `title`="Cumulative %", 
                                    `type`="number"))))}))$new(options=options))
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="descdesdim",
                title="Automatic Description of the Axes"))
            self$add(R6::R6Class(
                inherit = jmvcore::Group,
                active = list(
                    coordonnees = function() private$.items[["coordonnees"]],
                    contribution = function() private$.items[["contribution"]],
                    cosinus = function() private$.items[["cosinus"]]),
                private = list(),
                public=list(
                    initialize=function(options) {
                        super$initialize(
                            options=options,
                            name="individus",
                            title="Individual Tables")
                        self$add(jmvcore::Table$new(
                            options=options,
                            name="coordonnees",
                            title="Coordinates Table",
                            visible="(coordind)",
                            clearWith=list(
                                "nFactors"),
                            columns=list()))
                        self$add(jmvcore::Table$new(
                            options=options,
                            name="contribution",
                            title="Contributions Table",
                            visible="(contribind)",
                            clearWith=list(
                                "nFactors"),
                            columns=list()))
                        self$add(jmvcore::Table$new(
                            options=options,
                            name="cosinus",
                            title="Cosine Table",
                            visible="(cosind)",
                            clearWith=list(
                                "nFactors"),
                            columns=list()))}))$new(options=options))
            self$add(R6::R6Class(
                inherit = jmvcore::Group,
                active = list(
                    correlations = function() private$.items[["correlations"]],
                    contribution = function() private$.items[["contribution"]],
                    cosinus = function() private$.items[["cosinus"]]),
                private = list(),
                public=list(
                    initialize=function(options) {
                        super$initialize(
                            options=options,
                            name="variables",
                            title="Variable Tables")
                        self$add(jmvcore::Table$new(
                            options=options,
                            name="correlations",
                            title="Correlations Table",
                            visible="(corvar)",
                            clearWith=list(
                                "nFactors"),
                            columns=list()))
                        self$add(jmvcore::Table$new(
                            options=options,
                            name="contribution",
                            title="Contributions Table",
                            visible="(contribvar)",
                            clearWith=list(
                                "nFactors"),
                            columns=list()))
                        self$add(jmvcore::Table$new(
                            options=options,
                            name="cosinus",
                            title="Cosine Table",
                            visible="(cosvar)",
                            clearWith=list(
                                "nFactors"),
                            columns=list()))}))$new(options=options))}))

NappingBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "NappingBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "SEDA",
                name = "Napping",
                version = c(1,0,0),
                options = options,
                results = NappingResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE)
        }))

#' Analysis of Napping Data
#'
#' 
#' @param data .
#' @param actvars .
#' @param quantisup .
#' @param qualisup .
#' @param individus .
#' @param nFactors .
#' @param corvar .
#' @param contribvar .
#' @param cosvar .
#' @param coordind .
#' @param contribind .
#' @param cosind .
#' @param proba .
#' @param abs .
#' @param ord .
#' @param varact .
#' @param varillus .
#' @param varactillus .
#' @param limcosvar .
#' @param modact .
#' @param modillus .
#' @param modactillus .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$plotind} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$plotind2} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$plotind3} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$plotvar} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$plotvar2} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$plotvar3} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$plotgrp} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$eigengroup$eigen} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$descdesdim} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$individus$coordonnees} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$individus$contribution} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$individus$cosinus} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$variables$correlations} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$variables$contribution} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$variables$cosinus} \tab \tab \tab \tab \tab a table \cr
#' }
#'
#' @export
Napping <- function(
    data,
    actvars,
    quantisup,
    qualisup,
    individus,
    nFactors = 3,
    corvar = FALSE,
    contribvar = FALSE,
    cosvar = FALSE,
    coordind = FALSE,
    contribind = FALSE,
    cosind = FALSE,
    proba = 5,
    abs = 1,
    ord = 2,
    varact = FALSE,
    varillus = FALSE,
    varactillus = TRUE,
    limcosvar = 0,
    modact = FALSE,
    modillus = FALSE,
    modactillus = TRUE) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("Napping requires jmvcore to be installed (restart may be required)")

    if ( ! missing(actvars)) actvars <- jmvcore::resolveQuo(jmvcore::enquo(actvars))
    if ( ! missing(quantisup)) quantisup <- jmvcore::resolveQuo(jmvcore::enquo(quantisup))
    if ( ! missing(qualisup)) qualisup <- jmvcore::resolveQuo(jmvcore::enquo(qualisup))
    if ( ! missing(individus)) individus <- jmvcore::resolveQuo(jmvcore::enquo(individus))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(actvars), actvars, NULL),
            `if`( ! missing(quantisup), quantisup, NULL),
            `if`( ! missing(qualisup), qualisup, NULL),
            `if`( ! missing(individus), individus, NULL))

    for (v in qualisup) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])
    for (v in individus) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])

    options <- NappingOptions$new(
        actvars = actvars,
        quantisup = quantisup,
        qualisup = qualisup,
        individus = individus,
        nFactors = nFactors,
        corvar = corvar,
        contribvar = contribvar,
        cosvar = cosvar,
        coordind = coordind,
        contribind = contribind,
        cosind = cosind,
        proba = proba,
        abs = abs,
        ord = ord,
        varact = varact,
        varillus = varillus,
        varactillus = varactillus,
        limcosvar = limcosvar,
        modact = modact,
        modillus = modillus,
        modactillus = modactillus)

    analysis <- NappingClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

