
# This file is automatically generated, you probably don't want to edit this

QDAOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "QDAOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            prodeff = NULL,
            paneff = NULL,
            sensoatt = NULL,
            threshold = 5, ...) {

            super$initialize(
                package="SEDA",
                name="QDA",
                requiresData=TRUE,
                ...)

            private$..prodeff <- jmvcore::OptionVariable$new(
                "prodeff",
                prodeff,
                suggested=list(
                    "nominal"),
                permitted=list(
                    "factor"))
            private$..paneff <- jmvcore::OptionVariable$new(
                "paneff",
                paneff,
                suggested=list(
                    "nominal"),
                permitted=list(
                    "factor"))
            private$..sensoatt <- jmvcore::OptionVariables$new(
                "sensoatt",
                sensoatt,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"))
            private$..threshold <- jmvcore::OptionNumber$new(
                "threshold",
                threshold,
                default=5)

            self$.addOption(private$..prodeff)
            self$.addOption(private$..paneff)
            self$.addOption(private$..sensoatt)
            self$.addOption(private$..threshold)
        }),
    active = list(
        prodeff = function() private$..prodeff$value,
        paneff = function() private$..paneff$value,
        sensoatt = function() private$..sensoatt$value,
        threshold = function() private$..threshold$value),
    private = list(
        ..prodeff = NA,
        ..paneff = NA,
        ..sensoatt = NA,
        ..threshold = NA)
)

QDAResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "QDAResults",
    inherit = jmvcore::Group,
    active = list(
        resF = function() private$.items[["resF"]],
        resT = function() private$.items[["resT"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Characterization of the Stimulus Space")
            self$add(jmvcore::Table$new(
                options=options,
                name="resF",
                title="Identification of the Sensory Dimensions",
                columns=list(
                    list(
                        `name`="att", 
                        `title`="", 
                        `type`="text"),
                    list(
                        `name`="vtest", 
                        `title`="Vtest", 
                        `type`="number", 
                        `format`="zto,pvalue"),
                    list(
                        `name`="pvalue", 
                        `title`="p", 
                        `type`="number", 
                        `format`="zto,pvalue"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="resT",
                title="Sensory Description of the Stimuli",
                columns=list(
                    list(
                        `name`="component", 
                        `title`="", 
                        `type`="text", 
                        `combineBelow`=TRUE),
                    list(
                        `name`="var", 
                        `title`="Descriptor", 
                        `type`="text"),
                    list(
                        `name`="coeff", 
                        `title`="Coefficient", 
                        `type`="number"),
                    list(
                        `name`="adjmean", 
                        `title`="Adjusted mean", 
                        `type`="number"),
                    list(
                        `name`="pvalue", 
                        `title`="p", 
                        `type`="number", 
                        `format`="zto,pvalue"),
                    list(
                        `name`="vtest", 
                        `title`="Vtest", 
                        `type`="number"))))}))

QDABase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "QDABase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "SEDA",
                name = "QDA",
                version = c(1,0,0),
                options = options,
                results = QDAResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE)
        }))

#' Characterization of the Stimulus Space
#'
#' 
#' @param data .
#' @param prodeff .
#' @param paneff .
#' @param sensoatt .
#' @param threshold .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$resF} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$resT} \tab \tab \tab \tab \tab a table \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$resF$asDF}
#'
#' \code{as.data.frame(results$resF)}
#'
#' @export
QDA <- function(
    data,
    prodeff,
    paneff,
    sensoatt,
    threshold = 5) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("QDA requires jmvcore to be installed (restart may be required)")

    if ( ! missing(prodeff)) prodeff <- jmvcore::resolveQuo(jmvcore::enquo(prodeff))
    if ( ! missing(paneff)) paneff <- jmvcore::resolveQuo(jmvcore::enquo(paneff))
    if ( ! missing(sensoatt)) sensoatt <- jmvcore::resolveQuo(jmvcore::enquo(sensoatt))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(prodeff), prodeff, NULL),
            `if`( ! missing(paneff), paneff, NULL),
            `if`( ! missing(sensoatt), sensoatt, NULL))

    for (v in prodeff) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])
    for (v in paneff) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])

    options <- QDAOptions$new(
        prodeff = prodeff,
        paneff = paneff,
        sensoatt = sensoatt,
        threshold = threshold)

    analysis <- QDAClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

