
# This file is automatically generated, you probably don't want to edit this

QDABOOTOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "QDABOOTOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            prod = NULL,
            pane = NULL,
            senso = NULL,
            thresh = 5,
            nbsimul = 300,
            nbpane = 20,
            ind_gr_box = FALSE,
            var_gr_box = FALSE,
            abs = 1,
            ord = 2,
            scale_unit_box = TRUE,
            center_pane_box = TRUE,
            scale_pane_box = FALSE,
            level_search = 20,
            nFactors = 3,
            proba = 5, ...) {

            super$initialize(
                package="SEDA",
                name="QDABOOT",
                requiresData=TRUE,
                ...)

            private$..prod <- jmvcore::OptionVariable$new(
                "prod",
                prod,
                suggested=list(
                    "nominal"),
                permitted=list(
                    "factor"))
            private$..pane <- jmvcore::OptionVariable$new(
                "pane",
                pane,
                suggested=list(
                    "nominal"),
                permitted=list(
                    "factor"))
            private$..senso <- jmvcore::OptionVariables$new(
                "senso",
                senso,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"))
            private$..thresh <- jmvcore::OptionNumber$new(
                "thresh",
                thresh,
                default=5,
                min=0,
                max=100)
            private$..nbsimul <- jmvcore::OptionNumber$new(
                "nbsimul",
                nbsimul,
                default=300,
                min=10,
                max=1000)
            private$..nbpane <- jmvcore::OptionNumber$new(
                "nbpane",
                nbpane,
                default=20,
                min=2)
            private$..ind_gr_box <- jmvcore::OptionBool$new(
                "ind_gr_box",
                ind_gr_box,
                default=FALSE)
            private$..var_gr_box <- jmvcore::OptionBool$new(
                "var_gr_box",
                var_gr_box,
                default=FALSE)
            private$..abs <- jmvcore::OptionInteger$new(
                "abs",
                abs,
                default=1)
            private$..ord <- jmvcore::OptionInteger$new(
                "ord",
                ord,
                default=2)
            private$..scale_unit_box <- jmvcore::OptionBool$new(
                "scale_unit_box",
                scale_unit_box,
                default=TRUE)
            private$..center_pane_box <- jmvcore::OptionBool$new(
                "center_pane_box",
                center_pane_box,
                default=TRUE)
            private$..scale_pane_box <- jmvcore::OptionBool$new(
                "scale_pane_box",
                scale_pane_box,
                default=FALSE)
            private$..level_search <- jmvcore::OptionNumber$new(
                "level_search",
                level_search,
                default=20,
                min=1,
                max=100)
            private$..nFactors <- jmvcore::OptionInteger$new(
                "nFactors",
                nFactors,
                default=3)
            private$..proba <- jmvcore::OptionNumber$new(
                "proba",
                proba,
                default=5)

            self$.addOption(private$..prod)
            self$.addOption(private$..pane)
            self$.addOption(private$..senso)
            self$.addOption(private$..thresh)
            self$.addOption(private$..nbsimul)
            self$.addOption(private$..nbpane)
            self$.addOption(private$..ind_gr_box)
            self$.addOption(private$..var_gr_box)
            self$.addOption(private$..abs)
            self$.addOption(private$..ord)
            self$.addOption(private$..scale_unit_box)
            self$.addOption(private$..center_pane_box)
            self$.addOption(private$..scale_pane_box)
            self$.addOption(private$..level_search)
            self$.addOption(private$..nFactors)
            self$.addOption(private$..proba)
        }),
    active = list(
        prod = function() private$..prod$value,
        pane = function() private$..pane$value,
        senso = function() private$..senso$value,
        thresh = function() private$..thresh$value,
        nbsimul = function() private$..nbsimul$value,
        nbpane = function() private$..nbpane$value,
        ind_gr_box = function() private$..ind_gr_box$value,
        var_gr_box = function() private$..var_gr_box$value,
        abs = function() private$..abs$value,
        ord = function() private$..ord$value,
        scale_unit_box = function() private$..scale_unit_box$value,
        center_pane_box = function() private$..center_pane_box$value,
        scale_pane_box = function() private$..scale_pane_box$value,
        level_search = function() private$..level_search$value,
        nFactors = function() private$..nFactors$value,
        proba = function() private$..proba$value),
    private = list(
        ..prod = NA,
        ..pane = NA,
        ..senso = NA,
        ..thresh = NA,
        ..nbsimul = NA,
        ..nbpane = NA,
        ..ind_gr_box = NA,
        ..var_gr_box = NA,
        ..abs = NA,
        ..ord = NA,
        ..scale_unit_box = NA,
        ..center_pane_box = NA,
        ..scale_pane_box = NA,
        ..level_search = NA,
        ..nFactors = NA,
        ..proba = NA)
)

QDABOOTResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "QDABOOTResults",
    inherit = jmvcore::Group,
    active = list(
        plotind = function() private$.items[["plotind"]],
        plotvar = function() private$.items[["plotvar"]],
        eigenGr = function() private$.items[["eigenGr"]],
        dimdesc = function() private$.items[["dimdesc"]],
        plotspa = function() private$.items[["plotspa"]],
        hotGr = function() private$.items[["hotGr"]],
        plotpane = function() private$.items[["plotpane"]],
        plotvaria = function() private$.items[["plotvaria"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Multivariate Representation of the Stimulus Space")
            self$add(jmvcore::Image$new(
                options=options,
                name="plotind",
                title="Representation of the Stimuli",
                width=900,
                height=600,
                renderFun=".plotIndaxe"))
            self$add(jmvcore::Image$new(
                options=options,
                name="plotvar",
                title="Representation of the Sensory Attributes",
                width=600,
                height=600,
                renderFun=".plotVaraxe"))
            self$add(R6::R6Class(
                inherit = jmvcore::Group,
                active = list(
                    eigen_table = function() private$.items[["eigen_table"]]),
                private = list(),
                public=list(
                    initialize=function(options) {
                        super$initialize(
                            options=options,
                            name="eigenGr",
                            title="Eigenvalue Decomposition")
                        self$add(jmvcore::Table$new(
                            options=options,
                            name="eigen_table",
                            title="Eigenvalue and (Cumulative) Percentage of Variance",
                            columns=list(
                                list(
                                    `name`="facto", 
                                    `title`="", 
                                    `type`="text"),
                                list(
                                    `name`="eig", 
                                    `title`="Eigenvalue", 
                                    `type`="number"),
                                list(
                                    `name`="eig_pct", 
                                    `title`="% of variance", 
                                    `type`="number"),
                                list(
                                    `name`="eig_pct_cum", 
                                    `title`="Cumulative %", 
                                    `type`="number"))))}))$new(options=options))
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="dimdesc",
                title="Automatic Description of the Axes"))
            self$add(jmvcore::Image$new(
                options=options,
                name="plotspa",
                title="Representation of the Stimuli with Confidence Ellipses",
                width=900,
                height=600,
                renderFun=".plotSpace"))
            self$add(R6::R6Class(
                inherit = jmvcore::Group,
                active = list(
                    hot_table = function() private$.items[["hot_table"]]),
                private = list(),
                public=list(
                    initialize=function(options) {
                        super$initialize(
                            options=options,
                            name="hotGr",
                            title="Hotelling Test")
                        self$add(jmvcore::Table$new(
                            options=options,
                            name="hot_table",
                            title="p-values Associated with the Hotelling Test",
                            columns=list()))}))$new(options=options))
            self$add(jmvcore::Image$new(
                options=options,
                name="plotpane",
                visible="(ind_gr_box)",
                title="Individual Variability Around Stimuli",
                width=900,
                height=600,
                renderFun=".plotPane"))
            self$add(jmvcore::Image$new(
                options=options,
                name="plotvaria",
                visible="(var_gr_box)",
                title="Variability of the Sensory Attributes",
                width=600,
                height=600,
                renderFun=".plotvariavar"))}))

QDABOOTBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "QDABOOTBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "SEDA",
                name = "QDABOOT",
                version = c(1,0,0),
                options = options,
                results = QDABOOTResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE)
        }))

#' Multivariate Representation of the Stimulus Space
#'
#' 
#' @param data .
#' @param prod .
#' @param pane .
#' @param senso .
#' @param thresh .
#' @param nbsimul .
#' @param nbpane .
#' @param ind_gr_box .
#' @param var_gr_box .
#' @param abs .
#' @param ord .
#' @param scale_unit_box .
#' @param center_pane_box .
#' @param scale_pane_box .
#' @param level_search .
#' @param nFactors .
#' @param proba .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$plotind} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$plotvar} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$eigenGr$eigen_table} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$dimdesc} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$plotspa} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$hotGr$hot_table} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$plotpane} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$plotvaria} \tab \tab \tab \tab \tab an image \cr
#' }
#'
#' @export
QDABOOT <- function(
    data,
    prod,
    pane,
    senso,
    thresh = 5,
    nbsimul = 300,
    nbpane = 20,
    ind_gr_box = FALSE,
    var_gr_box = FALSE,
    abs = 1,
    ord = 2,
    scale_unit_box = TRUE,
    center_pane_box = TRUE,
    scale_pane_box = FALSE,
    level_search = 20,
    nFactors = 3,
    proba = 5) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("QDABOOT requires jmvcore to be installed (restart may be required)")

    if ( ! missing(prod)) prod <- jmvcore::resolveQuo(jmvcore::enquo(prod))
    if ( ! missing(pane)) pane <- jmvcore::resolveQuo(jmvcore::enquo(pane))
    if ( ! missing(senso)) senso <- jmvcore::resolveQuo(jmvcore::enquo(senso))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(prod), prod, NULL),
            `if`( ! missing(pane), pane, NULL),
            `if`( ! missing(senso), senso, NULL))

    for (v in prod) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])
    for (v in pane) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])

    options <- QDABOOTOptions$new(
        prod = prod,
        pane = pane,
        senso = senso,
        thresh = thresh,
        nbsimul = nbsimul,
        nbpane = nbpane,
        ind_gr_box = ind_gr_box,
        var_gr_box = var_gr_box,
        abs = abs,
        ord = ord,
        scale_unit_box = scale_unit_box,
        center_pane_box = center_pane_box,
        scale_pane_box = scale_pane_box,
        level_search = level_search,
        nFactors = nFactors,
        proba = proba)

    analysis <- QDABOOTClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

